language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'

script:
- npm run lint
- npm run build
- npm run test:coverage
- npm run test:codecov
- npm run docs

deploy:
  - provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
      secure: pjIJZBrAdRc8IZ1oQ3czqqD8uQ+9R7MgeGiRj00oFh6+e9jxANLJI6/zSAdlvWcUNy+2Npgoo4XgaGpuv5L9erPI7nLbfY4uGqMu30yERI+JRVYBGKqm0jPDshlkapD16x1fBV5PiRgfA8u4DcVA3yl0fvdmgcWnm+AmiZQ63ohn0WOkhnxDCHoYtBi5SJyd3ittSvTLny6kxrV94yKREeESP77csvhktPJeDAkeGlEJildNG6bYQ1phuL+V0htcPjqi9kve1vz5MSVWZxhv9p9gX2tt8IuFppr1OZaYj1Ap4ah9PjNOoh/xIhCOy0Udnhsm6RYbzxNlplMTFQuzUttvWtzobNH2A59Vhv6OIU0ZA1SnMWzhgviYr+cjRkLFw+QsEQ6fhmmuZSOa2PEDSyKYnjTds9HSHiXZGJSEZt/tpzCKu32d2fBqYdyUqOAhoSpQ/7VPfm346ZhQF2dREM7kdv+VLgtcOI6MoRfJeddZxw+iymqluZJqXQuLogqqrhDgek5DNJm2Xy6e9zjPQro+d8FiWVQB2tSf5X7tjz4d/oHFDOMd5VfhdZfnLN7wQHeDKbk7qW485pFYM/N1JTfbUYW5kJztCZ22SmqbW7ZSjRxTj7cQWNygfrSTS6iGVbpgfiV02hkjcytAFQ/uHyj6QszMQ5LICkVqLLVIlNA=
    on:
      tags: true
      repo: AckeeCZ/configuru
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: hFH6+EEkCD8cz88lcsvSxaGY9l8+t8EtqOwbvdPjPq139XG04JCUBZcFzzcMD3hMB2Gi6+S6M8TGc1EhoIS9KB81fJ9UgXxZn+sH95wpAvrB4MsXIE4fjyMUemhXAr89Ik1cA2PTQ3VJAhaRN4LcMaUOjYWLIDarw6aYL2tI9/iKiRzNYGoDegytvbq1tdS+VqSM2N3auVxUGlTU7pgG86EImhbl0RcMyOb3384P8IbDseFTgQbgBxmzfYvP0qx6dG+hoQC49Ae7wlmt2XYAD7xVaT0e7LLLGoxCuoMhxAK48M3wjzmpYyK9seBS/SpI30SN5EnazqdiVB6FydePk64yUNmllF1nf20IsdjMN3nSprR0rvkHS0EMesP/iEYsLj3BDWKjJ8X/kWOyIo/DxiEKrG5VS1IMaTxBNbaWazvo3wJIn/KUHO3Ugg+Bf9AUPpq7Paz7rWCBBg3CJhiCOYvPlHx53Onky9nE2BXi7q4VZqXf30kPAkXN/J9Vw/joujfwwBuO4NVxrRswt/BQ+D0yKhyoEhqEoWTOJnWr9yrm6fsQPZFTPB7mBywHqbmc4jroJTQ8xILqMTfIu/9PjjA8lXznY7hTLRcPvsP96VKnI8V1OPfgRMVJ1cIuWvZyBSoDoIamw9/r+zlMzJ1VcHTDglcZNSe82uXzjhsk1mU=
    keep-history: true
    local-dir: ./docs
    verbose: true
    on:
      branch: master